local filetypes = {
  "aspnetcorerazor",
  "astro",
  "astro-markdown",
  "blade",
  "clojure",
  "django-html",
  "htmldjango",
  "edge",
  "eelixir",
  "elixir",
  "ejs",
  "erb",
  "eruby",
  "gohtml",
  "gohtmltmpl",
  "haml",
  "handlebars",
  "hbs",
  "html",
  "htmlangular",
  "html-eex",
  "heex",
  "jade",
  "leaf",
  "liquid",
  "markdown",
  "mdx",
  "mustache",
  "njk",
  "nunjucks",
  "php",
  "razor",
  "slim",
  "twig",
  "css",
  "less",
  "postcss",
  "sass",
  "scss",
  "stylus",
  "sugarss",
  "javascript",
  "javascriptreact",
  "reason",
  "rescript",
  "typescript",
  "typescriptreact",
  "vue",
  "svelte",
  "templ",
}

return function(capabilities)
  local caps = vim.tbl_deep_extend("force", {}, capabilities, {
    workspace = {
      didChangeWatchedFiles = { dynamicRegistration = true },
    },
  })

  vim.lsp.config("tailwindcss", {
    cmd = { "tailwindcss-language-server", "--stdio" },
    capabilities = caps,
    filetypes = filetypes,
  })
end
